/**
 * data.js - Base de données des verbes allemands irréguliers
 * Contient tous les verbes utilisés dans l'application
 */

const VERBES = [
  { "inf": "an/bieten", "pres": "er bietet an", "pret": "er bot an", "parf": "er hat angeboten", "sens": "offrir" },
  { "inf": "an/fangen", "pres": "er fängt an", "pret": "er fing an", "parf": "er hat angefangen", "sens": "commencer" },
  { "inf": "an/kommen", "pres": "er kommt an", "pret": "er kam an", "parf": "er ist angekommen", "sens": "arriver" },
  { "inf": "an/rufen", "pres": "er ruft an", "pret": "er rief an", "parf": "er hat angerufen", "sens": "appeler au téléphone" },
  { "inf": "an/ziehen", "pres": "er zieht an", "pret": "er zog an", "parf": "er hat angezogen", "sens": "mettre (un vêtement)" },
  { "inf": "aus/geben", "pres": "er gibt aus", "pret": "er gab aus", "parf": "er hat ausgegeben", "sens": "dépenser" },
  { "inf": "aus/sehen", "pres": "er sieht aus", "pret": "er sah aus", "parf": "er hat ausgesehen", "sens": "avoir l'air" },
  { "inf": "beginnen", "pres": "er beginnt", "pret": "er begann", "parf": "er hat begonnen", "sens": "commencer" },
  { "inf": "bekommen", "pres": "er bekommt", "pret": "er bekam", "parf": "er hat bekommen", "sens": "recevoir, obtenir" },
  { "inf": "begreifen", "pres": "er begreift", "pret": "er begriff", "parf": "er hat begriffen", "sens": "comprendre" },
  { "inf": "beschließen", "pres": "er beschließt", "pret": "er beschloss", "parf": "er hat beschlossen", "sens": "décider" },
  { "inf": "beschreiben", "pres": "er beschreibt", "pret": "er beschrieb", "parf": "er hat beschrieben", "sens": "décrire" },
  { "inf": "bleiben", "pres": "er bleibt", "pret": "er blieb", "parf": "er ist geblieben", "sens": "rester" },
  { "inf": "brechen", "pres": "er bricht", "pret": "er brach", "parf": "er hat gebrochen", "sens": "casser" },
  { "inf": "bringen", "pres": "er bringt", "pret": "er brachte", "parf": "er hat gebracht", "sens": "apporter" },
  { "inf": "denken", "pres": "er denkt", "pret": "er dachte", "parf": "er hat gedacht", "sens": "penser" },
  { "inf": "ein/laden", "pres": "er lädt ein", "pret": "er lud ein", "parf": "er hat eingeladen", "sens": "inviter" },
  { "inf": "ein/schlafen", "pres": "er schläft ein", "pret": "er schlief ein", "parf": "er ist eingeschlafen", "sens": "s'endormir" },
  { "inf": "empfangen", "pres": "er empfängt", "pret": "er empfing", "parf": "er hat empfangen", "sens": "recevoir" },
  { "inf": "empfehlen", "pres": "er empfiehlt", "pret": "er empfahl", "parf": "er hat empfohlen", "sens": "recommander" },
  { "inf": "erhalten", "pres": "er erhält", "pret": "er erhielt", "parf": "er hat erhalten", "sens": "obtenir" },
  { "inf": "ertragen", "pres": "er erträgt", "pret": "er ertrug", "parf": "er hat ertragen", "sens": "supporter" },
  { "inf": "essen", "pres": "er isst", "pret": "er aß", "parf": "er hat gegessen", "sens": "manger" },
  { "inf": "fahren", "pres": "er fährt", "pret": "er fuhr", "parf": "er ist gefahren", "sens": "aller (en véhicule)" },
  { "inf": "fallen", "pres": "er fällt", "pret": "er fiel", "parf": "er ist gefallen", "sens": "tomber" },
  { "inf": "fangen", "pres": "er fängt", "pret": "er fing", "parf": "er hat gefangen", "sens": "attraper" },
  { "inf": "fern/sehen", "pres": "er sieht fern", "pret": "er sah fern", "parf": "er hat ferngesehen", "sens": "regarder la télé" },
  { "inf": "finden", "pres": "er findet", "pret": "er fand", "parf": "er hat gefunden", "sens": "trouver" },
  { "inf": "fliegen", "pres": "er fliegt", "pret": "er flog", "parf": "er ist geflogen", "sens": "voler" },
  { "inf": "fliehen", "pres": "er flieht", "pret": "er floh", "parf": "er ist geflohen", "sens": "fuir" },
  { "inf": "fressen", "pres": "er frisst", "pret": "er fraß", "parf": "er hat gefressen", "sens": "manger (animal)" },
  { "inf": "geben", "pres": "er gibt", "pret": "er gab", "parf": "er hat gegeben", "sens": "donner" },
  { "inf": "gehen", "pres": "er geht", "pret": "er ging", "parf": "er ist gegangen", "sens": "aller" },
  { "inf": "gefallen", "pres": "er gefällt", "pret": "er gefiel", "parf": "er hat gefallen", "sens": "plaire" },
  { "inf": "gewinnen", "pres": "er gewinnt", "pret": "er gewann", "parf": "er hat gewonnen", "sens": "gagner" },
  { "inf": "halten", "pres": "er hält", "pret": "er hielt", "parf": "er hat gehalten", "sens": "tenir" },
  { "inf": "helfen", "pres": "er hilft", "pret": "er half", "parf": "er hat geholfen", "sens": "aider" },
  { "inf": "kennen", "pres": "er kennt", "pret": "er kannte", "parf": "er hat gekannt", "sens": "connaître" },
  { "inf": "kommen", "pres": "er kommt", "pret": "er kam", "parf": "er ist gekommen", "sens": "venir" },
  { "inf": "lassen", "pres": "er lässt", "pret": "er ließ", "parf": "er hat gelassen", "sens": "laisser" },
  { "inf": "laufen", "pres": "er läuft", "pret": "er lief", "parf": "er ist gelaufen", "sens": "courir" },
  { "inf": "leiden", "pres": "er leidet", "pret": "er litt", "parf": "er hat gelitten", "sens": "souffrir" },
  { "inf": "lesen", "pres": "er liest", "pret": "er las", "parf": "er hat gelesen", "sens": "lire" },
  { "inf": "mit/helfen", "pres": "er hilft mit", "pret": "er half mit", "parf": "er hat mitgeholfen", "sens": "donner un coup de main" },
  { "inf": "mit/nehmen", "pres": "er nimmt mit", "pret": "er nahm mit", "parf": "er hat mitgenommen", "sens": "emporter" },
  { "inf": "nehmen", "pres": "er nimmt", "pret": "er nahm", "parf": "er hat genommen", "sens": "prendre" },
  { "inf": "reiten", "pres": "er reitet", "pret": "er ritt", "parf": "er ist geritten", "sens": "monter à cheval" },
  { "inf": "scheinen", "pres": "er scheint", "pret": "er schien", "parf": "er hat geschienen", "sens": "sembler/briller" },
  { "inf": "schlafen", "pres": "er schläft", "pret": "er schlief", "parf": "er hat geschlafen", "sens": "dormir" },
  { "inf": "schließen", "pres": "er schließt", "pret": "er schloss", "parf": "er hat geschlossen", "sens": "fermer" },
  { "inf": "schreiben", "pres": "er schreibt", "pret": "er schrieb", "parf": "er hat geschrieben", "sens": "écrire" },
  { "inf": "schreien", "pres": "er schreit", "pret": "er schrie", "parf": "er hat geschrien", "sens": "crier" },
  { "inf": "schwimmen", "pres": "er schwimmt", "pret": "er schwamm", "parf": "er ist geschwommen", "sens": "nager" },
  { "inf": "sehen", "pres": "er sieht", "pret": "er sah", "parf": "er hat gesehen", "sens": "voir" },
  { "inf": "sein", "pres": "er ist", "pret": "er war", "parf": "er ist gewesen", "sens": "être" },
  { "inf": "singen", "pres": "er singt", "pret": "er sang", "parf": "er hat gesungen", "sens": "chanter" },
  { "inf": "sitzen", "pres": "er sitzt", "pret": "er saß", "parf": "er hat gesessen", "sens": "être assis" },
  { "inf": "sprechen", "pres": "er spricht", "pret": "er sprach", "parf": "er hat gesprochen", "sens": "parler" },
  { "inf": "stehen", "pres": "er steht", "pret": "er stand", "parf": "er hat gestanden", "sens": "être debout" },
  { "inf": "steigen", "pres": "er steigt", "pret": "er stieg", "parf": "er ist gestiegen", "sens": "monter" },
  { "inf": "sterben", "pres": "er stirbt", "pret": "er starb", "parf": "er ist gestorben", "sens": "mourir" },
  { "inf": "sich streiten", "pres": "er streitet sich", "pret": "er stritt sich", "parf": "er hat gestritten", "sens": "se disputer" },
  { "inf": "tragen", "pres": "er trägt", "pret": "er trug", "parf": "er hat getragen", "sens": "porter" },
  { "inf": "treffen", "pres": "er trifft", "pret": "er traf", "parf": "er hat getroffen", "sens": "rencontrer" },
  { "inf": "treiben", "pres": "er treibt", "pret": "er trieb", "parf": "er hat getrieben", "sens": "pousser / pratiquer" },
  { "inf": "trinken", "pres": "er trinkt", "pret": "er trank", "parf": "er hat getrunken", "sens": "boire" },
  { "inf": "tun", "pres": "er tut", "pret": "er tat", "parf": "er hat getan", "sens": "faire" },
  { "inf": "übertreiben", "pres": "er übertreibt", "pret": "er übertrieb", "parf": "er hat übertreiben", "sens": "exagérer" },
  { "inf": "verbieten", "pres": "er verbietet", "pret": "er verbot", "parf": "er hat verboten", "sens": "interdire" },
  { "inf": "verbringen", "pres": "er verbringt", "pret": "er verbrachte", "parf": "er hat verbracht", "sens": "passer du temps" },
  { "inf": "vergessen", "pres": "er vergisst", "pret": "er vergaß", "parf": "er hat vergessen", "sens": "oublier" },
  { "inf": "vergleichen", "pres": "er vergleicht", "pret": "er verglich", "parf": "er hat verglichen", "sens": "comparer" },
  { "inf": "verlassen", "pres": "er verlässt", "pret": "er verließ", "parf": "er hat verlassen", "sens": "quitter, abandonner" },
  { "inf": "verlieren", "pres": "er verliert", "pret": "er verlor", "parf": "er hat verloren", "sens": "perdre" },
  { "inf": "versprechen", "pres": "er verspricht", "pret": "er versprach", "parf": "er hat versprochen", "sens": "promettre" },
  { "inf": "verschwinden", "pres": "er verschwindet", "pret": "er verschwand", "parf": "er ist verschwunden", "sens": "disparaître" },
  { "inf": "verstehen", "pres": "er versteht", "pret": "er verstand", "parf": "er hat verstanden", "sens": "comprendre" },
  { "inf": "vor/schlagen", "pres": "er schlägt vor", "pret": "er schlug vor", "parf": "er hat vorgeschlagen", "sens": "proposer" },
  { "inf": "werden", "pres": "er wird", "pret": "er wurde", "parf": "er ist geworden", "sens": "devenir" },
  { "inf": "werfen", "pres": "er wirft", "pret": "er warf", "parf": "er hat geworfen", "sens": "jeter" },
  { "inf": "wissen", "pres": "er weiß", "pret": "er wusste", "parf": "er hat gewusst", "sens": "savoir" },
  { "inf": "ziehen", "pres": "er zieht", "pret": "er zog", "parf": "er hat gezogen", "sens": "tirer" },
  { "inf": "zwingen", "pres": "er zwingt", "pret": "er zwang", "parf": "er hat gezwungen", "sens": "forcer" },
  { "inf": "backen", "pres": "er bäckt", "pret": "er backte", "parf": "er hat gebacken", "sens": "cuire au four" },
  { "inf": "befehlen", "pres": "er befiehlt", "pret": "er befahl", "parf": "er hat befohlen", "sens": "ordonner" },
  { "inf": "biegen", "pres": "er biegt", "pret": "er bog", "parf": "er hat gebogen", "sens": "plier" },
  { "inf": "bieten", "pres": "er bietet", "pret": "er bot", "parf": "er hat geboten", "sens": "offrir" },
  { "inf": "binden", "pres": "er bindet", "pret": "er band", "parf": "er hat gebunden", "sens": "attacher" },
  { "inf": "bitten", "pres": "er bittet", "pret": "er bat", "parf": "er hat gebeten", "sens": "demander" },
  { "inf": "blasen", "pres": "er bläst", "pret": "er blies", "parf": "er hat geblasen", "sens": "souffler" },
  { "inf": "fließen", "pres": "er fließt", "pret": "er floss", "parf": "er ist geflossen", "sens": "couler" },
  { "inf": "frieren", "pres": "er friert", "pret": "er fror", "parf": "er hat gefroren", "sens": "avoir froid / geler" },
  { "inf": "graben", "pres": "er gräbt", "pret": "er grub", "parf": "er hat gegraben", "sens": "creuser" },
  { "inf": "hängen", "pres": "er hängt", "pret": "er hing", "parf": "er hat gehangen", "sens": "être suspendu" },
  { "inf": "heißen", "pres": "er heißt", "pret": "er hieß", "parf": "er hat geheißen", "sens": "s'appeler" },
  { "inf": "kneifen", "pres": "er kneift", "pret": "er kniff", "parf": "er hat gekniffen", "sens": "pincer" },
  { "inf": "laden", "pres": "er lädt", "pret": "er lud", "parf": "er hat geladen", "sens": "charger" },
  { "inf": "liegen", "pres": "er liegt", "pret": "er lag", "parf": "er hat gelegen", "sens": "être couché" },
  { "inf": "lügen", "pres": "er lügt", "pret": "er log", "parf": "er hat gelogen", "sens": "mentir" },
  { "inf": "messen", "pres": "er misst", "pret": "er maß", "parf": "er hat gemessen", "sens": "mesurer" },
  { "inf": "pfeifen", "pres": "er pfeift", "pret": "er pfiff", "parf": "er hat gepfiffen", "sens": "siffler" },
  { "inf": "raten", "pres": "er rät", "pret": "er riet", "parf": "er hat geraten", "sens": "conseiller / deviner" },
  { "inf": "schlagen", "pres": "er schlägt", "pret": "er schlug", "parf": "er hat geschlagen", "sens": "frapper" },
  { "inf": "schneiden", "pres": "er schneidet", "pret": "er schnitt", "parf": "er hat geschnitten", "sens": "couper" },
  { "inf": "schweigen", "pres": "er schweigt", "pret": "er schwieg", "parf": "er hat geschwiegen", "sens": "se taire" },
  { "inf": "springen", "pres": "er springt", "pret": "er sprang", "parf": "er ist gesprungen", "sens": "sauter" },
  { "inf": "waschen", "pres": "er wäscht", "pret": "er wusch", "parf": "er hat gewaschen", "sens": "laver" },
  { "inf": "wachsen", "pres": "er wächst", "pret": "er wuchs", "parf": "er ist gewachsen", "sens": "grandir / pousser" },
  { "inf": "weichen", "pres": "er weicht", "pret": "er wich", "parf": "er ist gewichen", "sens": "céder" },
  { "inf": "weisen", "pres": "er weist", "pret": "er wies", "parf": "er hat gewiesen", "sens": "indiquer" },
  { "inf": "schmelzen", "pres": "er schmilzt", "pret": "er schmolz", "parf": "er ist geschmolzen", "sens": "fondre" },
  { "inf": "streiten", "pres": "er streitet", "pret": "er stritt", "parf": "er hat gestritten", "sens": "se disputer" },
  { "inf": "verzeihen", "pres": "er verzeiht", "pret": "er verzieh", "parf": "er hat verziehen", "sens": "pardonner" },
  { "inf": "winden", "pres": "er windet", "pret": "er wand", "parf": "er hat gewunden", "sens": "tordre" },
  { "inf": "sinken", "pres": "er sinkt", "pret": "er sank", "parf": "er ist gesunken", "sens": "couler" },
  { "inf": "stinken", "pres": "er stinkt", "pret": "er stank", "parf": "er hat gestunken", "sens": "puer" },
  { "inf": "schelten", "pres": "er schilt", "pret": "er schalt", "parf": "er hat gescholten", "sens": "gronder" },
  { "inf": "scheren", "pres": "er schert", "pret": "er schor", "parf": "er hat geschoren", "sens": "tondre" },
  { "inf": "schieben", "pres": "er schiebt", "pret": "er schob", "parf": "er hat geschoben", "sens": "pousser" },
  { "inf": "schwören", "pres": "er schwört", "pret": "er schwor", "parf": "er hat geschworen", "sens": "jurer" },
  { "inf": "sieden", "pres": "er siedet", "pret": "er sott", "parf": "er hat gesotten", "sens": "bouillir" },
  { "inf": "verderben", "pres": "er verdirbt", "pret": "er verdarb", "parf": "er ist verdorben", "sens": "gâcher" },
  { "inf": "wiegen", "pres": "er wiegt", "pret": "er wog", "parf": "er hat gewogen", "sens": "peser" },
  { "inf": "zeihen", "pres": "er zeiht", "pret": "er zieh", "parf": "er hat geziehen", "sens": "accuser" },
  { "inf": "zerschneiden", "pres": "er zerschneidet", "pret": "er zerschnitt", "parf": "er hat zerschnitten", "sens": "découper" },
  { "inf": "ab/biegen", "pres": "er biegt ab", "pret": "er bog ab", "parf": "er hat abgebogen", "sens": "tourner" },
  { "inf": "ab/nehmen", "pres": "er nimmt ab", "pret": "er nahm ab", "parf": "er hat abgenommen", "sens": "perdre du poids / enlever" },
  { "inf": "an/binden", "pres": "er bindet an", "pret": "er band an", "parf": "er hat angebunden", "sens": "attacher" },
  { "inf": "auf/brechen", "pres": "er bricht auf", "pret": "er brach auf", "parf": "er ist aufgebrochen", "sens": "partir / forcer" },
  { "inf": "auf/essen", "pres": "er isst auf", "pret": "er aß auf", "parf": "er hat aufgegessen", "sens": "finir de manger" },
  { "inf": "auf/fallen", "pres": "er fällt auf", "pret": "er fiel auf", "parf": "er ist aufgefallen", "sens": "frapper l'attention" },
  { "inf": "auf/geben", "pres": "er gibt auf", "pret": "er gab auf", "parf": "er hat aufgegeben", "sens": "abandonner" },
  { "inf": "auf/stehen", "pres": "er steht auf", "pret": "er stand auf", "parf": "er ist aufgestanden", "sens": "se lever" },
  { "inf": "aus/steigen", "pres": "er steigt aus", "pret": "er stieg aus", "parf": "er ist ausgestiegen", "sens": "descendre (véhicule)" },
  { "inf": "bei/beißen", "pres": "er beißt zu", "pret": "er biss zu", "parf": "er hat zugebissen", "sens": "mordre" },
  { "inf": "behalten", "pres": "er behält", "pret": "er behielt", "parf": "er hat behalten", "sens": "garder" },
  { "inf": "bei/bringen", "pres": "er bringt bei", "pret": "er brachte bei", "parf": "er hat beigebracht", "sens": "apprendre (enseigner)" },
  { "inf": "ein/werfen", "pres": "er wirft ein", "pret": "er warf ein", "parf": "er hat eingeworfen", "sens": "jeter dedans" },
  { "inf": "ein/ziehen", "pres": "er zieht ein", "pret": "er zog ein", "parf": "er ist eingezogen", "sens": "emménager" },
  { "inf": "empfinden", "pres": "er empfindet", "pret": "er empfand", "parf": "er hat empfunden", "sens": "ressentir" },
  { "inf": "ent/kommen", "pres": "er kommt ent", "pret": "er kam ent", "parf": "er ist entkommen", "sens": "s'échapper" },
  { "inf": "ent/stehen", "pres": "er entsteht", "pret": "er entstand", "parf": "er ist entstanden", "sens": "naître / surgir" },
  { "inf": "erkennen", "pres": "er erkennt", "pret": "er erkannte", "parf": "er hat erkannt", "sens": "reconnaître" },
  { "inf": "erwägen", "pres": "er erwägt", "pret": "er erwog", "parf": "er hat erwogen", "sens": "envisager" },
  { "inf": "fest/halten", "pres": "er hält fest", "pret": "er hielt fest", "parf": "er hat festgehalten", "sens": "retenir" },
  { "inf": "fort/fahren", "pres": "er fährt fort", "pret": "er fuhr fort", "parf": "er ist fortgefahren", "sens": "continuer / partir" },
  { "inf": "fort/gehen", "pres": "er geht fort", "pret": "er ging fort", "parf": "er ist fortgegangen", "sens": "s'en aller" },
  { "inf": "frei/geben", "pres": "er gibt frei", "pret": "er gab frei", "parf": "er hat freigegeben", "sens": "libérer" },
  { "inf": "hin/fallen", "pres": "er fällt hin", "pret": "er fiel hin", "parf": "er ist hingefallen", "sens": "tomber" },
  { "inf": "hin/kommen", "pres": "er kommt hin", "pret": "er kam hin", "parf": "er ist hingekommen", "sens": "arriver" },
  { "inf": "los/lassen", "pres": "er lässt los", "pret": "er ließ los", "parf": "er hat losgelassen", "sens": "lâcher" },
  { "inf": "mit/bringen", "pres": "er bringt mit", "pret": "er brachte mit", "parf": "er hat mitgebracht", "sens": "apporter avec soi" },
  { "inf": "nach/denken", "pres": "er denkt nach", "pret": "er dachte nach", "parf": "er hat nachgedacht", "sens": "réfléchir" },
  { "inf": "preis/geben", "pres": "er gibt preis", "pret": "er gab preis", "parf": "er hat preisgegeben", "sens": "divulguer" },
  { "inf": "statt/finden", "pres": "er findet statt", "pret": "er fand statt", "parf": "er hat stattgefunden", "sens": "avoir lieu" },
  { "inf": "teil/nehmen", "pres": "er nimmt teil", "pret": "er nahm teil", "parf": "er hat teilgenommen", "sens": "participer" },
  { "inf": "über/geben", "pres": "er gibt über", "pret": "er gab über", "parf": "er hat übergeben", "sens": "remettre / vomir" },
  { "inf": "über/nehmen", "pres": "er übernimmt", "pret": "er übernahm", "parf": "er hat übernommen", "sens": "reprendre / assumer" },
  { "inf": "um/steigen", "pres": "er steigt um", "pret": "er stieg um", "parf": "er ist umgestiegen", "sens": "changer (transport)" },
  { "inf": "unter/gehen", "pres": "er geht unter", "pret": "er ging unter", "parf": "er ist untergegangen", "sens": "sombrer / se coucher" },
  { "inf": "ver/geben", "pres": "er vergibt", "pret": "er vergab", "parf": "er hat vergeben", "sens": "pardonner" },
  { "inf": "ver/meiden", "pres": "er vermeidet", "pret": "er vermied", "parf": "er hat vermieden", "sens": "éviter" },
  { "inf": "vor/lesen", "pres": "er liest vor", "pret": "er las vor", "parf": "er hat vorgelesen", "sens": "lire à voix haute" },
  { "inf": "weg/werfen", "pres": "er wirft weg", "pret": "er warf weg", "parf": "er hat weggeworfen", "sens": "jeter" },
  { "inf": "weiter/geben", "pres": "er gibt weiter", "pret": "er gab weiter", "parf": "er hat weitergegeben", "sens": "transmettre" },
  { "inf": "zu/binden", "pres": "er bindet zu", "pret": "er band zu", "parf": "er hat zugebunden", "sens": "attacher" },
  { "inf": "zu/geben", "pres": "er gibt zu", "pret": "er gab zu", "parf": "er hat zugegeben", "sens": "avouer" },
  { "inf": "zu/nehmen", "pres": "er nimmt zu", "pret": "er nahm zu", "parf": "er hat zugenommen", "sens": "prendre du poids" },
  { "inf": "zurück/kommen", "pres": "er kommt zurück", "pret": "er kam zurück", "parf": "er ist zurückgekommen", "sens": "revenir" },
  { "inf": "zusammen/kommen", "pres": "er kommt zusammen", "pret": "er kam zusammen", "parf": "er ist zusammengekommen", "sens": "se réunir" }
];

// Constantes de configuration
const CONFIG = {
  GROUP_SIZE: 10,
  TAILLE_PALIER: 5,
  SEUIL_MAITRISE: 3,
  TAUX_REVISION: 0.2,
  QUESTION_TYPES: ["classique", "sens_inf", "inf_sens"]
};
